# SFusion (SYNAPSE Fusion) Mapper - "Day Zero" ETL Configuration Tool
# Copyright (C) 2026 Gabriel Moraes - Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# File: src/services/math_engine.py
# Author: Gabriel Moraes
# Date: May 2026

import logging
import polars as pl
from typing import List

from src.core.schemas import KinematicMap
from src.utils.i18n import backend_i18n

logger = logging.getLogger(__name__)

class MathEngine:
    """
    Vector Engine and AST Compiler.
    Operates exclusively on CPU and RAM.
    Receives the validated Blueprint (KinematicMap) generated by AI or heuristics
    and translates it into Native Expressions (Computational Graphs) in Polars.
    """
    
    @staticmethod
    def compile_ast(schema: KinematicMap) -> List[pl.Expr]:
        """
        Generates the Abstract Syntax Tree (Polars Expressions) for the physical variables.
        Reads keys and normalizes columns. Physics calculations are deferred to the aggregation phase.
        """
        exprs = []
        logger.debug(backend_i18n.t("math_engine.compiling_ast"))

        def safe_div(num_expr: pl.Expr, den_expr: pl.Expr) -> pl.Expr:
            return pl.when(den_expr == 0.0).then(pl.lit(None)).otherwise(num_expr / den_expr)
            
        def num_col(col_name: str) -> pl.Expr:
            return pl.col(col_name).cast(pl.Float64, strict=False)
        
        # =========================================================================
        # 1. SPEED / VELOCITY (Normalized)
        # =========================================================================
        speed_expr = None
        if schema.speed_col:
            speed_expr = num_col(schema.speed_col)
            logger.debug(backend_i18n.t("math_engine.mapping_speed_direct"))
        elif schema.distance_col and schema.time_col:
            logger.debug(backend_i18n.t("math_engine.compiling_speed_derivative"))
            speed_expr = safe_div(num_col(schema.distance_col), num_col(schema.time_col))

        if speed_expr is None: speed_expr = pl.lit(None)
        exprs.append(speed_expr.alias("speed_val"))

        # =========================================================================
        # 2. FLOW / VOLUME (Normalized)
        # =========================================================================
        flow_expr = None
        if schema.flow_col:
            flow_expr = num_col(schema.flow_col)
            logger.debug(backend_i18n.t("math_engine.mapping_flow_direct", col=schema.flow_col))

        if flow_expr is None: flow_expr = pl.lit(None)
        exprs.append(flow_expr.alias("flow_val"))

        # =========================================================================
        # 3. INTENSITY / DENSITY (Normalized)
        # =========================================================================
        intensity_expr = None
        if schema.intensity_col:
            intensity_expr = num_col(schema.intensity_col)
            logger.debug(backend_i18n.t("math_engine.mapping_intensity_direct"))
        elif schema.occupancy_col:
            logger.debug(backend_i18n.t("math_engine.compiling_intensity_occupancy"))
            intensity_expr = num_col(schema.occupancy_col)
            
        if intensity_expr is None: intensity_expr = pl.lit(None)
        exprs.append(intensity_expr.alias("intensity_val"))

        return exprs

    @staticmethod
    def compile_aggregations(columns: List[str]) -> List[pl.Expr]:
        """
        Creates aggregation expressions for a DataFrame containing multiple vehicle events.
        Calculates Space Mean Speed (Harmonic Mean), Flow (Count / Time) and Intensity (Flow / Speed) 
        for physics accuracy on microscopic data.
        """
        agg_exprs = []
        
        # 1. Space Mean Speed (Harmonic Mean: N / sum(1/v))
        hm_expr = pl.lit(None)
        if "speed_val" in columns:
            v_col = pl.col("speed_val").drop_nulls()
            
            den_sum = (1.0 / pl.when(v_col == 0.0).then(None).otherwise(v_col)).sum()
            
            hm_expr = (
                pl.when(v_col.count() > 0)
                .then(
                    pl.when(den_sum > 0.0)
                    .then(v_col.count() / den_sum)
                    .otherwise(0.0)
                )
                .otherwise(None)
            )
            agg_exprs.append(hm_expr.alias("speed_val"))
        
        # 2. Flow (q = Count / Time OR Sum of explicit flow)
        final_flow = pl.lit(None)
        if "event_timestamp" in columns:
            ts = pl.col("event_timestamp").cast(pl.Datetime, strict=False)
            time_span_hours = (ts.max() - ts.min()).dt.total_milliseconds() / 3600000.0
            time_span_hours = pl.when((time_span_hours > 0.0) & time_span_hours.is_not_null()).then(time_span_hours).otherwise(1.0)
            
            micro_flow = pl.count() / time_span_hours
            
            if "flow_val" in columns:
                # Use explicit flow if provided, else fall back to micro_flow
                final_flow = pl.when(pl.col("flow_val").drop_nulls().count() > 0).then(pl.col("flow_val").sum()).otherwise(micro_flow)
            else:
                final_flow = micro_flow
            agg_exprs.append(final_flow.alias("flow_val"))
        else:
            if "flow_val" in columns:
                final_flow = pl.col("flow_val").sum()
                agg_exprs.append(final_flow.alias("flow_val"))
        
        # 3. Intensity (k = q / v OR Mean of explicit intensity)
        if "intensity_val" in columns:
            derived_intensity = pl.when(hm_expr.is_not_null() & (hm_expr > 0.0)).then(final_flow / hm_expr).otherwise(0.0)
            final_intensity = pl.when(pl.col("intensity_val").drop_nulls().count() > 0).then(pl.col("intensity_val").mean()).otherwise(derived_intensity)
            agg_exprs.append(final_intensity.alias("intensity_val"))
        else:
            # If intensity_val isn't even in columns, we still derive it if we can
            derived_intensity = pl.when(hm_expr.is_not_null() & (hm_expr > 0.0)).then(final_flow / hm_expr).otherwise(0.0)
            agg_exprs.append(derived_intensity.alias("intensity_val"))
        
        # 4. Keep essential metadata
        if "event_timestamp" in columns:
            agg_exprs.append(pl.col("event_timestamp").max().alias("event_timestamp"))
        
        # Flexibly find lat and lon columns
        lat_col = next((c for c in columns if c.lower().endswith("lat")), None)
        if lat_col:
            agg_exprs.append(pl.col(lat_col).first().alias("lat"))
            
        lon_col = next((c for c in columns if c.lower().endswith("lon")), None)
        if lon_col:
            agg_exprs.append(pl.col(lon_col).first().alias("lon"))
        
        return agg_exprs

