# SFusion (SYNAPSE Fusion) Mapper - "Day Zero" ETL Configuration Tool
# Copyright (C) 2026 Gabriel Moraes - Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# File: src/services/math_engine.py
# Author: Gabriel Moraes
# Date: May 2026

import logging
import polars as pl
from typing import List

from src.core.schemas import KinematicMap

logger = logging.getLogger(__name__)

class MathEngine:
    """
    Vector Engine and AST Compiler.
    Operates exclusively on CPU and RAM.
    Receives the validated Blueprint (KinematicMap) generated by AI or heuristics
    and translates it into Native Expressions (Computational Graphs) in Polars.
    """
    
    @staticmethod
    def compile_ast(schema: KinematicMap) -> List[pl.Expr]:
        """
        Generates the Abstract Syntax Tree (Polars Expressions) for the three physical variables.
        Implements the Fundamental Equation of Traffic Flow: q (flow) = k (density) * v (speed)
        """
        exprs = []
        logger.debug("Compiling Computational Graph (AST) from KinematicMap...")

        # Helper function for mathematically safe division in AST to avoid ZeroDivisionError
        def safe_div(num_expr: pl.Expr, den_expr: pl.Expr) -> pl.Expr:
            return pl.when(den_expr == 0.0).then(pl.lit(None)).otherwise(num_expr / den_expr)
            
        # Helper to treat columns strictly as numeric tensors
        def num_col(col_name: str) -> pl.Expr:
            return pl.col(col_name).cast(pl.Float64, strict=False)
        
        # =========================================================================
        # 1. SPEED / VELOCITY (v = ds/dt OR v = q/k)
        # =========================================================================
        speed_expr = None
        if schema.speed_col:
            speed_expr = num_col(schema.speed_col)
            logger.debug("-> Mapping Speed directly from column.")
        elif schema.distance_col and schema.time_col:
            logger.debug("-> Compiling Kinematic Derivative: speed = distance / time")
            speed_expr = safe_div(num_col(schema.distance_col), num_col(schema.time_col))
        elif schema.flow_col and schema.intensity_col:
            logger.debug("-> Compiling Speed from Fundamental Relation: speed = flow / intensity")
            speed_expr = safe_div(num_col(schema.flow_col), num_col(schema.intensity_col))

        if speed_expr is None: speed_expr = pl.lit(None)
        exprs.append(speed_expr.alias("speed_val"))

        # =========================================================================
        # 2. FLOW / VOLUME (q = k * v)
        # =========================================================================
        flow_expr = None
        if schema.flow_col:
            flow_expr = num_col(schema.flow_col)
            logger.debug(f"-> Mapping Flow directly from column '{schema.flow_col}'.")
        elif schema.intensity_col and speed_expr is not None:
            logger.debug("-> Compiling Flow from Fundamental Relation: flow = intensity * speed")
            flow_expr = num_col(schema.intensity_col) * speed_expr
        elif schema.intensity_col and (schema.distance_col and schema.time_col):
            logger.debug("-> Compiling Flow: flow = intensity * (distance / time)")
            v_expr = safe_div(num_col(schema.distance_col), num_col(schema.time_col))
            flow_expr = num_col(schema.intensity_col) * v_expr

        if flow_expr is None: flow_expr = pl.lit(None)
        exprs.append(flow_expr.alias("flow_val"))

        # =========================================================================
        # 3. INTENSITY / DENSITY (k = q / v OR derived from Occupancy)
        # =========================================================================
        intensity_expr = None
        if schema.intensity_col:
            intensity_expr = num_col(schema.intensity_col)
            logger.debug("-> Mapping Intensity directly from column.")
        elif flow_expr is not None and speed_expr is not None:
            logger.debug("-> Compiling Intensity from Fundamental Relation: intensity = flow / speed")
            intensity_expr = safe_div(flow_expr, speed_expr)
        elif flow_expr is not None and (schema.distance_col and schema.time_col):
            logger.debug("-> Compiling Intensity: intensity = flow / (distance / time)")
            v_expr = safe_div(num_col(schema.distance_col), num_col(schema.time_col))
            intensity_expr = safe_div(flow_expr, v_expr)
        elif schema.occupancy_col:
            logger.debug("-> Compiling Intensity proportional to Occupancy.")
            intensity_expr = num_col(schema.occupancy_col)
            
        if intensity_expr is None: intensity_expr = pl.lit(None)
        exprs.append(intensity_expr.alias("intensity_val"))

        return exprs

    @staticmethod
    def compile_aggregations(columns: List[str]) -> List[pl.Expr]:
        """
        Creates aggregation expressions for a DataFrame containing multiple vehicle events.
        Calculates Space Mean Speed (Harmonic Mean) for physics accuracy.
        """
        agg_exprs = []
        
        # 1. Space Mean Speed (Harmonic Mean: N / sum(1/v))
        if "speed_val" in columns:
            v_col = pl.col("speed_val").drop_nulls()
            
            # Harmonic Mean: N / sum(1/v). If v=0, we ignore it in denominator. 
            # If ALL speeds are 0, sum(1/v) becomes 0, which would cause division by zero (Infinity).
            den_sum = (1.0 / pl.when(v_col == 0.0).then(None).otherwise(v_col)).sum()
            
            hm_expr = (
                pl.when(v_col.count() > 0)
                .then(
                    pl.when(den_sum > 0.0)
                    .then(v_col.count() / den_sum)
                    .otherwise(0.0) # If all speeds are 0, return 0 instead of Infinity
                )
                .otherwise(None)
            )
            agg_exprs.append(hm_expr.alias("speed_val"))
        
        # 2. Flow (Sum of flows/counts)
        if "flow_val" in columns:
            agg_exprs.append(pl.col("flow_val").sum().alias("flow_val"))
        
        # 3. Intensity (Mean)
        if "intensity_val" in columns:
            agg_exprs.append(pl.col("intensity_val").mean().alias("intensity_val"))
        
        # 4. Keep essential metadata
        if "event_timestamp" in columns:
            agg_exprs.append(pl.col("event_timestamp").max().alias("event_timestamp"))
        
        # Flexibly find lat and lon columns
        lat_col = next((c for c in columns if c.lower().endswith("lat")), None)
        if lat_col:
            agg_exprs.append(pl.col(lat_col).first().alias("lat"))
            
        lon_col = next((c for c in columns if c.lower().endswith("lon")), None)
        if lon_col:
            agg_exprs.append(pl.col(lon_col).first().alias("lon"))
        
        return agg_exprs

